name: embedder

services:
  cargo-ci:
    build:
      context: .
      dockerfile: docker/Cargo.Dockerfile
      args:
        - MODE=ci
    image: denwong47/embedder-cargo
    volumes:
    - .:/root/embedder
  convert-model:
    build:
      context: .
      dockerfile: docker/ConvertModel.Dockerfile
    image: denwong47/embedder-convert-model
    volumes:
    - ./models:/root/models
