name: embedder

services:
  convert-model:
    build:
      context: .
      dockerfile: docker/ConvertModel.Dockerfile
    image: denwong47/embedder-convert-model
    volumes:
    - ./models:/root/models
    environment:
    - MODEL=${MODEL}
