name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main", "development", "staging" ]
    paths:
      - 'src/**'
      - 'crates/**'
      - '.github/workflows/rust-CI.yml'
  pull_request:
    branches: [ "main", "development", "staging" ]
    paths:
      - 'src/**'
      - 'crates/**'
      - '.github/workflows/rust-CI.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:

    runs-on: ubuntu-latest
    env:
      LIBTORCH_USE_PYTORCH: 1

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Restore cached Cargo artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Restore cached Models
      id: cache-models-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          .cache/models
        key: ${{ runner.os }}-models
    # TODO Can matrix this
    - uses: ./.github/actions/build-onnx
      if: steps.cache-models-restore.outputs.cache-hit != 'true'
      id: build-onnx-minilm
      name: Build ONNX Model - all-MiniLM-L6-v2
      with:
        model: 'sentence-transformers/all-MiniLM-L6-v2'
        output: '.cache/models'
    - uses: ./.github/actions/build-onnx
      if: steps.cache-models-restore.outputs.cache-hit != 'true'
      id: build-onnx-mpnet
      name: Build ONNX Model - all-mpnet-base-v2
      with:
        model: 'sentence-transformers/all-mpnet-base-v2'
        output: '.cache/models'
    - name: Show cached models
      working-directory: .cache/models
      run: find $(pwd)
    - uses: hecrj/setup-rust-action@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Check clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests (Library)
      working-directory: crates/embedder-lib
      env:
        RUST_LOG: debug
        MODEL_PATH: ../../.cache/models
      run: cargo test --all-features
    - name: Run tests (API)
      env:
        RUST_LOG: debug
      run: cargo test --all-features
    - name: Cache Models
      if: ${{ success() && steps.cache-models-restore.outputs.cache-hit != 'true' }}
      id: cache-models-save
      uses: actions/cache/save@v4
      with:
        path: |
          .cache/models
        key: ${{ runner.os }}-models
